# Permalinks
permalink: /:year-:month-:day/:title

# Setup
title: Jihye Leee
baseurl: ""
url: "https://daeheejeong.github.io"

# Assets
sass:
  sass_dir: _sass
  style: :compressed

# Build settings
markdown: kramdown

# About
author:
  name: Daehee Jeong
  url: https://daeheejeong.github.io
  email: dev.daehee.jeong@gmail.com
  github: daeheejeong

# Custom vars
version: 3.4.1
github:
  repo: https://github.com/daeheejeong/daeheejeong.github.io